---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/ambv/black
    rev: "23.12.0"
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: "5.13.1"
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/adrienverge/yamllint.git
    rev: "v1.33.0"
    hooks:
      - id: yamllint
        language_version: python3
