# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.3"
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
